name: Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for PoC"
        required: true
        type: string
      should_upload_artifacts:
        description: "Should upload artifacts"
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      should_upload_artifacts:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: x86_64-unknown-linux-gnu
            path: README.md # Dùng file tạm để test cho nhanh
            asset_name: "test-${{ inputs.tag_name }}"

    steps:
      - uses: actions/checkout@v4

      - name: Archive assets (Vulnerable Step)
        run: |
          # Đây là nơi lỗ hổng xảy ra do thiếu dấu ngoặc kép quanh ${{ matrix.asset_name }}
          echo "Testing injection..."
          gzip -c ${{ matrix.path }} > test.gz && mv test.gz ${{ matrix.asset_name }}.gz
